# Generated by Django 4.1.5 on 2023-05-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
