# Generated by Django 4.1.5 on 2023-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('registration', '0002_user_access_user_age_user_f_name_user_l_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finalised_courses',
            field=models.ManyToManyField(to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(),
        ),
    ]
