# Generated by Django 4.1.5 on 2023-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_quiz'),
        ('registration', '0003_user_finalised_courses_alter_user_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='finalised_courses',
            field=models.ManyToManyField(blank=True, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
