# Generated by Django 4.1.5 on 2023-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificat_alter_courses_category_and_more'),
        ('registration', '0004_alter_user_access_alter_user_finalised_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificats',
            field=models.ManyToManyField(blank=True, to='courses.certificat'),
        ),
    ]
