# Generated by Django 4.1.5 on 2023-05-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate_delete_certificat'),
        ('registration', '0005_user_certificats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificats',
            field=models.ManyToManyField(blank=True, to='courses.certificate'),
        ),
    ]
