# Generated by Django 4.1.5 on 2023-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=55)),
                ('content', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
