# Generated by Django 4.1.5 on 2023-05-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='quiz',
            field=models.TextField(default='essa'),
            preserve_default=False,
        ),
    ]
