# Generated by Django 4.1.5 on 2023-05-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='quiz',
            field=models.TextField(blank=True),
        ),
    ]
